### ISSUE TITLE
US2

### ISSUE THREAD

**Issue by binhtendo** [binhtendo/capstone-project#3]
## Value Proposition

As a user 
I want to have a list of all places 
so that i can get an overview of all places
​

## Description
the list shows me the result of my search
​
<img width="225" alt="US2" src="https://user-images.githubusercontent.com/122276595/223150636-180fd1a7-bee5-4735-879b-cf1aaccb740a.png">

## Acceptance Criteria

All places are displayed as a list
Each place title is displayed
eventually with a picture​

## Tasks

-
-
-
      ​

## Complexity

... (T-Shirt Sizes XS to XL)

**Comment by pung-one** [comment]
same here! looks good apart from nav bar

**Comment by binhtendo** [comment]
> same here! looks good apart from nav bar

you are absolutely right. primarily it is about the function that a list is displayed.
