### ISSUE TITLE
To-Do Page

### ISSUE THREAD

**Issue by binhtendo** [binhtendo/capstone-project#8]
## Value Proposition

**As an user
**I want to** put things on a packing list with the help of a to-do list (or checklist)
**so that** i don't forget to pack anything for the trip. You can also switch to the todo page in the navbar
​

## Description

... (Wireframe, scribble, design or text)
​
<img width="188" alt="todo" src="https://user-images.githubusercontent.com/122276595/225865803-cf7cc346-98b1-4cf0-9d92-b08534e8fdc2.png">

## Acceptance Criteria

- create an input field with an add button
- entries are listed in a card
- checkbox before each entry
- for the moment a delete button
      ​

## Tasks

- install uselocalstoragestate
- install uid
- create Form component with function Form
- create List component
- create /todo in pages with function todo, handledeleteTodo and handletoggleCheckTodo
      ​

**Comment by binhtendo** [comment]
> If you include a `delete` button you also have to include its functionality. The same goes for the edit button. If you don't want to include the functionality, leave out the buttons.

the delete-function will be implemented. But the edit-function will not be implemented yet. it is drawn a little bit wrong in the picture. That is why "for the moment" a functional delete button. is it still okay to do it that way?

**Comment by Kheirah** [comment]
Sure, as long as you fully implement your features, you're all good!
